"""
DHRUVNETRA - FastAPI Backend Test Suite
Tests all endpoints: Root, Health, and POST /api/what-if pipeline.
"""

import sys
from pathlib import Path

# Automatically ensure project root is in sys.path
_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent.parent
for _p in [str(_PROJECT_ROOT), str(_SCRIPT_DIR.parent)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from fastapi.testclient import TestClient

try:
    from backend.app.main import app
except ModuleNotFoundError:
    from app.main import app

client = TestClient(app)


def run_api_tests():
    print("=" * 70)
    print(" RUNNING DHRUVNETRA FASTAPI BACKEND API TEST SUITE")
    print("=" * 70)

    passed = 0
    total = 0

    def check(condition: bool, name: str):
        nonlocal passed, total
        total += 1
        if condition:
            print(f" [+] PASS: {name}")
            passed += 1
        else:
            print(f" [!] FAIL: {name}")

    # --------------------------------------------------------------------------
    # TEST 1: Root & Health Endpoints
    # --------------------------------------------------------------------------
    print("\n--- TEST 1: Health & Diagnostics ---")
    r_root = client.get("/")
    check(r_root.status_code == 200, "Root index returns 200 OK")
    check("DHRUVNETRA" in r_root.json()["service"], "Root service name correct")

    r_health = client.get("/api/health")
    check(r_health.status_code == 200, "Health check returns 200 OK")
    check(r_health.json()["status"] == "healthy", "Health status is healthy")

    # --------------------------------------------------------------------------
    # TEST 2: Primary Required Query - Gen 1 at Maitri for 7 Hours
    # --------------------------------------------------------------------------
    print("\n--- TEST 2: POST /api/what-if ('What if Generator 1 at Maitri is turned off for 7 hours?') ---")
    payload = {"query": "What if Generator 1 at Maitri is turned off for 7 hours?"}
    r = client.post("/api/what-if", json=payload)
    check(r.status_code == 200, "What-If returns 200 OK")

    data = r.json()
    check(data["success"] is True, "Response success is True")
    check("scenario" in data, "Response contains 'scenario'")
    check("baseline" in data, "Response contains 'baseline'")
    check("prediction" in data, "Response contains 'prediction'")
    check("impact" in data, "Response contains 'impact'")
    check("risk" in data, "Response contains 'risk'")
    check("recommendation" in data, "Response contains 'recommendation'")
    check("explanation" in data, "Response contains 'explanation'")

    sc = data["scenario"]
    check(sc["station"] == "Maitri", "Scenario station is Maitri")
    check(sc["component"] == "generator", "Scenario component is generator")
    check(sc["component_id"] == "G1", "Scenario component_id is G1")
    check(sc["action"] == "shutdown", "Scenario action is shutdown")
    check(sc["duration_hours"] == 7.0, "Scenario duration is 7.0")

    pred = data["prediction"]
    check(pred["deficit_kw"] == 0.0, "Maitri has zero power deficit on G1 shutdown (G2 carries base load)")
    check(len(pred["trajectory"]) > 0, "Trajectory chart data generated by ML predictor")

    risk = data["risk"]
    check(risk["overall_risk"] in ["LOW", "MEDIUM"], "Risk level is LOW or MEDIUM for standard generator maintenance")

    exp_clean = data['explanation'].encode('ascii', 'replace').decode('ascii')
    rec_clean = data['recommendation'].encode('ascii', 'replace').decode('ascii')
    print(f"    AI Explanation: {exp_clean}")
    print(f"    Recommendation: {rec_clean}")

    # --------------------------------------------------------------------------
    # TEST 3: Bharati Station Query
    # --------------------------------------------------------------------------
    print("\n--- TEST 3: POST /api/what-if ('What if Gen 2 at Bharati trips for 12 hrs?') ---")
    payload3 = {"query": "What if Gen 2 at Bharati trips for 12 hrs?"}
    r3 = client.post("/api/what-if", json=payload3)
    check(r3.status_code == 200, "Bharati scenario returns 200 OK")
    data3 = r3.json()
    check(data3["scenario"]["station"] == "Bharati", "Bharati correctly identified as station")
    check(data3["scenario"]["component_id"] == "G2", "G2 correctly identified as component")

    # --------------------------------------------------------------------------
    # TEST 4: Out of bounds duration rejected with 400
    # --------------------------------------------------------------------------
    print("\n--- TEST 4: Out-of-bounds duration rejection (> 168 hrs) ---")
    payload4 = {"query": "What if Generator 1 at Maitri is turned off for 300 hours?"}
    r4 = client.post("/api/what-if", json=payload4)
    check(r4.status_code == 400, "300 hours duration rejected with 400 Bad Request")
    check("validation_errors" in r4.json() or "detail" in r4.json(), "Validation error details returned in response")

    # --------------------------------------------------------------------------
    # TEST 5: Empty query rejected with 400
    # --------------------------------------------------------------------------
    print("\n--- TEST 5: Empty query rejection ---")
    payload5 = {"query": "   "}
    r5 = client.post("/api/what-if", json=payload5)
    check(r5.status_code == 400, "Empty query rejected with 400 Bad Request")

    print("\n" + "=" * 70)
    print(f" FASTAPI BACKEND TEST RESULTS: {passed} / {total} PASSED")
    print("=" * 70)

    if passed != total:
        exit(1)


if __name__ == "__main__":
    run_api_tests()
